### ISSUE TITLE
App in development mode, can't access oauth

### ISSUE THREAD

**Issue by arvind-iyer** [syncany/syncany-plugin-dropbox#9]
![image](https://cloud.githubusercontent.com/assets/5451184/12970745/8bea5b58-d0cd-11e5-96a2-dcf0dd952b5b.png)
Is this just me or is it an actual issue?

**Comment by pimotte** [comment]
Yep, this is an actual issue: https://github.com/syncany/syncany/issues/521https://github.com/syncany/syncany/issues/521

Closing this because we use the main project for issue tracking (see #1).
